services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    environment:
       MONGO_INITDB_DATABASE: order_db
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTERNERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  app:
    image: order-service:latest
    container_name: order-service
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
volumes:
  mongo-data:

